### ISSUE TITLE
Licence listed as proprietary in gnome-software

### ISSUE THREAD

**Issue by mjog** [flathub/com.frac_tion.teleport#1]
As per the summary, gnome-software lists Teleport on flathub as proprietary. Minor, but you know, freeeeeeedom. ;)

PS: Cool looking app, an Android client would be great!

**Comment by TingPing** [comment]
`AGPL-3.0+` which latest upstream has is valid: https://spdx.org/licenses/

Maybe a GNOME-Software issue?

**Comment by jsparber** [comment]
I filled a bug report for this
https://bugzilla.gnome.org/show_bug.cgi?id=789615

**Comment by nedrichards** [comment]
Resolved upstream - looking at the release dates it should be in GNOME Software 3.28 and newer
